# Generated by Django 4.0.5 on 2023-05-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_customer_delete_addtocart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='order_notes',
        ),
    ]
